### PR TITLE
Don't clobber libiomp5md.dll

### LINKED ISSUE #8: DLL load error - incompatible libiomp5md.dll
Both this (`openmp`) package and the defaults `intel-openmp` install `libiomp5md.dll` into `/Library/bin`:

```
λ ls C:\Miniconda3\pkgs\openmp-6.0.0-vc14_0\Library\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l       11/03/2018     10:48         615424 libiomp5md.dll
-a---l       11/03/2018     10:48         615424 libomp.dll
```
```
λ ls C:\Miniconda3\pkgs\intel-openmp-2018.0.0-8\Library\bin

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---l       23/03/2018      2:22        1343744 libiomp5md.dll
-a---l       23/03/2018      2:22        3755008 libiomp5md.pdb
-a---l       23/03/2018      2:22          81664 libiompstubs5md.dll
```
This means that installing one when the other is already present will ***overwrite*** the existing `libiomp5md.dll`.

Unfortunately these two dlls do not appear to be compatible as using the `libiomp5md.dll` provided by the `openmp` package will break `pytorch`, resulting in a DLL load error:
```
ImportError: DLL load failed: The operating system cannot run %1.
```

Tested on win64/py36

### PR DESCRIPTION
**Pull request by dhirschfeld**
Fixes #8

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Did my best there - don't have linux easily available to test so YMMV.

**Comment by jakirkham** [comment]
Thanks. Looks pretty good.

We can add a verbose flag to get that info from CIs.

Also it appears `libiomp5md.dll` is in `lib` too. A little strange, but we should get that one too.

Should we worry about `libgomp` as a possibility on Windows? Not seeing it in the latest binary I grabbed, but figured I'd ask. :)

Last thing would be a build number bump to get new packages out the door.

**Comment by dhirschfeld** [comment]
Are you sure `libiomp5md.dll` is there on linux? Linux doesn't use dlls does it?
In anyc ase, I did check the bz2 file on linux & osx and I don't see it in there?

https://anaconda.org/conda-forge/openmp/6.0.0/download/linux-64/openmp-6.0.0-0.tar.bz2
image

**Comment by dhirschfeld** [comment]
> *Should we worry about libgomp as a possibility on Windows?*

Since I don't see it in the bz2 I'm happy to punt on that until it becomes a problem, but am also happy to do whatever is best.

**Comment by jakirkham** [comment]
> Are you sure `libiomp5md.dll` is there on linux?

No, was meaning Windows. It shows up in `Library\bin` and `Library\lib` for some reason.

**Comment by dhirschfeld** [comment]
ping!

I'm keen to get this PR merged. I think it's good to go and the tests pass - is there anything else which needs doing?

**Comment by jakirkham** [comment]
Thanks @dhirschfeld. Sorry this fell off the radar.

**Pull request merged**
