### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by xoviat**

### CODE REVIEW

**Comment by xoviat** [comment]
@conda-forge-admin Please rerender

**Comment by xoviat** [comment]
cc @isuruf

**Comment by xoviat** [comment]
cc @conda-forge/openmp

**Comment by isuruf** [comment]
I think `clangdev` needs to be fixed before this

**Comment by xoviat** [comment]
That's not correct. Because clangdev depends on llvmdev, we only need to fix llvmdev.

**Pull request merged**
