### PR TITLE
openmp 16.0.0.rc1

### PR DESCRIPTION
**Pull request by h-vetinari**
Follows https://github.com/conda-forge/llvmdev-feedstock/pull/195; osx didn't get built yet due to failing tests, but will continue with the rest of the arches in the meantime.

Builds on #70, which didn't get merged in the 15 cycle, so the rc branch is still at 14...

### CODE REVIEW

**Comment by h-vetinari** [comment]
So, compared to the errors about `PRIxPTR` (which apparently isn't available in the glibc 2.12 `inttypes.h`[^1]) before https://github.com/conda-forge/openmp-feedstock/pull/77/commits/4918835bcd46de1356a72c1da16dc6fa0244d636, we now get `undefined reference to 'memcpy@GLIBC_2.14'`. I think this is due to [this](https://stackoverflow.com/a/54815372). We may be hitting the limits of what's possible with glibc 2.12 here.

[^1]: the compiler says `note: 'PRIxPTR' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?`, but it's already included; one file contains the superset `#include <cstdint>`, and the other contains what should be the C-equivalent `#include <inttypes.h>`

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
i think this helped.

**Comment by h-vetinari** [comment]
Thanks @hmaarrfk !

Doesn't this mean that we'd need a run-dependence on the newer sysroot here?

**Comment by h-vetinari** [comment]
> Doesn't this mean that we'd need a run-dependence on the newer sysroot here?

@isuruf, maybe you could give some guidance here?

**Comment by isuruf** [comment]
Just add `-Wl,--allow-shlib-undefined` to link flags when linking. We do this in the compiler activation flags

**Comment by h-vetinari** [comment]
> Just add `-Wl,--allow-shlib-undefined` to link flags when linking. We do this in the compiler activation flags

Thanks, that did the trick! Anything else here you'd like to review/comment on? (use of sysroot 2.17, move to cos7, ...)

Otherwise I'm planning to merge this later today (it's only for the rc-channel anyway, we'll still have a deeper review once 16 goes GA).

**Pull request merged**
